// Engine tests: run tests/engine/**/*.test.ts inside a headless Godot and report TAP.
//   bun run test:engine [--filter <text>] [--keep]
// What it does: writes a generated entry script + scene under tests/_runner/ (gitignored), builds the game AND that entry in one
// Bun pass (same plugin, so decorators, @onready and connect(fn) work in tests), launches the configured binary on the scene,
// and judges the output: every test must print `ok`, the TAP plan must match the number of results (a hang or a crash cannot
// pass), and no engine ERROR or leak line may appear. Exit code 0 only when all of that holds. Afterwards the generated files and
// their compiled bundle are deleted (--keep leaves them for debugging), so a test run never leaves anything a release could ship.
// The test kit itself is tools/test-kit.ts; src/ never imports it. Pure logic tests are `bun test` (tests/logic), not this.
import { spawn } from "node:child_process";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { buildProject } from "./build.ts";
import { requireGodot } from "./config.ts";

const ROOT = join(import.meta.dir, "..");
const RUNNER_DIR = join(ROOT, "tests", "_runner");
const BUNDLE_DIR = join(ROOT, ".godot", "GodotJS", "tests");
const argv = process.argv.slice(2);
const filterAt = argv.indexOf("--filter");
const filter = filterAt >= 0 ? argv[filterAt + 1] : undefined;
const keep = argv.includes("--keep");

const clean = (): void => {
  rmSync(RUNNER_DIR, { recursive: true, force: true });
  rmSync(BUNDLE_DIR, { recursive: true, force: true });
};
const fail = (message: string): never => {
  console.error(`FAIL engine tests: ${message}`);
  if (!keep) clean();
  process.exit(1);
};

const files = [...new Bun.Glob("tests/engine/**/*.test.ts").scanSync(ROOT)].filter((f) => !filter || f.includes(filter)).sort();
if (files.length === 0) fail(`no test files match tests/engine/**/*.test.ts${filter ? ` with "${filter}"` : ""}`);

clean();
mkdirSync(RUNNER_DIR, { recursive: true });
const entry = join(RUNNER_DIR, "entry.ts");
writeFileSync(
  entry,
  `// generated by tools/test.ts, do not edit
import "../../polyfills/web-globals.js";
import { Node } from "godot";
import { runAll } from "../../tools/test-kit";
${files.map((f) => `import "../../${f}";`).join("\n")}
export default class TestRunner extends Node {
  _ready(): void {
    runAll((line) => console.log(line), this).then((code) => this.get_tree().quit(code));
  }
}
`,
);
writeFileSync(
  join(RUNNER_DIR, "runner.tscn"),
  `[gd_scene load_steps=2 format=3]\n\n[ext_resource type="Script" path="res://tests/_runner/entry.ts" id="1"]\n\n[node name="TestRunner" type="Node"]\nscript = ExtResource("1")\n`,
);

console.log(`building ${files.length} engine test file(s) ...`);
if (!(await buildProject(ROOT, [entry]))) fail("the build failed (see above)");

const binary = requireGodot();
// --quit-after is only a safety net (frames); the runner quits itself with the exit code. The wall-clock timeout catches a hang.
// The engine runs in its OWN process group and the whole group is killed on a timeout, on Ctrl-C and on exit: Bun.spawnSync's
// `timeout` kills only the direct child and cannot run signal handlers, so a hung engine could outlive this runner.
const run = await new Promise<{ stdout: string; stderr: string; exitCode: number | null }>((done) => {
  const child = spawn(binary, ["--headless", "--path", ROOT, "res://tests/_runner/runner.tscn", "--quit-after", "20000"], { stdio: ["ignore", "pipe", "pipe"], detached: true });
  const killGroup = (): void => { try { process.kill(-child.pid!, "SIGKILL"); } catch { /* already gone */ } };
  let stdout = "", stderr = "";
  child.stdout.on("data", (d) => (stdout += d));
  child.stderr.on("data", (d) => (stderr += d));
  const timer = setTimeout(killGroup, 120_000);
  process.on("exit", killGroup);
  for (const sig of ["SIGINT", "SIGTERM"] as const) process.on(sig, () => { killGroup(); if (!keep) clean(); process.exit(sig === "SIGINT" ? 130 : 143); });
  child.on("close", (exitCode) => { clearTimeout(timer); killGroup(); done({ stdout, stderr, exitCode }); });
});
const out = (run.stdout + run.stderr).replace(/\x1b\[[0-9;]*m/g, "").replace(/^\[JS\] /gm, "");
const lines = out.split("\n");
if (!keep) clean();

const tap = lines.filter((l) => /^(ok|not ok) \d+ - /.test(l));
const plan = Number(out.match(/^1\.\.(\d+)$/m)?.[1] ?? -1);
const problems: string[] = [];
if (tap.length === 0) problems.push(`no TAP output from the engine (exit ${run.exitCode}); the first lines of its log are below`);
else if (tap.length !== plan) problems.push(`the plan said ${plan} tests but ${tap.length} reported (a test hung or the engine died)`);
if (run.exitCode !== 0 && tap.every((l) => l.startsWith("ok"))) problems.push(`the engine exited with code ${run.exitCode}`);
const noisy = lines.filter((l) => /^(ERROR|SCRIPT ERROR|FATAL)\b|^WARNING: .*(leak|ObjectDB)|leaked|ObjectDB instances/.test(l));
if (noisy.length) problems.push(`engine log problems:\n  ${noisy.slice(0, 5).join("\n  ")}`);

console.log(lines.filter((l) => /^(TAP|1\.\.|ok|not ok|  #|# )/.test(l)).join("\n"));
const failed = tap.filter((l) => l.startsWith("not ok")).length;
if (failed > 0 || problems.length > 0) {
  if (tap.length === 0) console.log(out.split("\n").slice(0, 40).join("\n"));
  for (const p of problems) console.error(`FAIL engine tests: ${p}`);
  console.error(`FAIL engine tests: ${failed} of ${tap.length} failed (${files.map((f) => relative("tests", f)).join(", ")})`);
  process.exit(1);
}
console.log(`PASS engine tests (${tap.length} in ${files.length} file(s))`);
